# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
